// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1020cj2Mlb9vreOyjlhVsi4HvJMQD7Ps',
    appId: '1:829915151381:web:391ef927af792a4f6b621c',
    messagingSenderId: '829915151381',
    projectId: 'erp-danf',
    authDomain: 'erp-danf.firebaseapp.com',
    storageBucket: 'erp-danf.firebasestorage.app',
    measurementId: 'G-7GS4YL5VK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr7adhTqvVJN275Cf6TDWBjcVcKjMol7w',
    appId: '1:829915151381:android:8a89a64a6d8e69426b621c',
    messagingSenderId: '829915151381',
    projectId: 'erp-danf',
    storageBucket: 'erp-danf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB78fgJc2osrgqufHvGIrcosbVCY1mRvXk',
    appId: '1:829915151381:ios:5756472ddef2dc2f6b621c',
    messagingSenderId: '829915151381',
    projectId: 'erp-danf',
    storageBucket: 'erp-danf.firebasestorage.app',
    iosBundleId: 'com.example.erpDanf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB78fgJc2osrgqufHvGIrcosbVCY1mRvXk',
    appId: '1:829915151381:ios:5756472ddef2dc2f6b621c',
    messagingSenderId: '829915151381',
    projectId: 'erp-danf',
    storageBucket: 'erp-danf.firebasestorage.app',
    iosBundleId: 'com.example.erpDanf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1020cj2Mlb9vreOyjlhVsi4HvJMQD7Ps',
    appId: '1:829915151381:web:89346f6042b567f96b621c',
    messagingSenderId: '829915151381',
    projectId: 'erp-danf',
    authDomain: 'erp-danf.firebaseapp.com',
    storageBucket: 'erp-danf.firebasestorage.app',
    measurementId: 'G-QSCSQC1581',
  );
}
